definitions:
  model.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /send-to-support:
    post:
      consumes:
      - application/json
      description: Принимает новое обращение с параметрами mail, title, message, createdAt
        и files.
      parameters:
      - description: Email пользователя
        in: formData
        name: mail
        required: true
        type: string
      - description: Заголовок обращения
        in: formData
        name: title
        required: true
        type: string
      - description: Сообщение
        in: formData
        name: message
        required: true
        type: string
      - description: Дата и время создания обращения в формате RFC3339
        in: formData
        name: createdAt
        required: true
        type: string
      - description: Файлы, прикрепленные к обращению
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/model.MessageResponse'
        "400":
          description: Ошибка в запросе
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Принимает сообщение (обращение).
      tags:
      - EmailService
swagger: "2.0"
